spring:
  application:
    name: streamhub-realtime-gateway
  config:
    import:
      - optional:nacos:streamhub-shared.yaml?group=${NACOS_CONFIG_GROUP:STREAMHUB}&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=${NACOS_CONFIG_GROUP:STREAMHUB}&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        enabled: ${NACOS_CONFIG_ENABLED:true}
    gateway:
      routes:
        - id: live-service-websocket
          uri: lb:ws://streamhub-live
          predicates:
            - Path=/ws/**

server:
  port: ${REALTIME_GATEWAY_PORT:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
