spring:
  application:
    name: streamhub-gateway
  config:
    import:
      - optional:nacos:streamhub-shared.yaml?group=${NACOS_CONFIG_GROUP:STREAMHUB}&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=${NACOS_CONFIG_GROUP:STREAMHUB}&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        enabled: ${NACOS_CONFIG_ENABLED:true}
    gateway:
      routes:
        - id: auth-service
          uri: lb://streamhub-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://streamhub-user
          predicates:
            - Path=/api/v1/users/**
        - id: live-service-api
          uri: lb://streamhub-live
          predicates:
            - Path=/api/v1/live/**,/api/v1/gifts,/api/v1/wallet/**,/api/v1/activities/**,/api/v1/gift-orders/**,/api/v1/activity-orders/**

server:
  port: ${SERVER_PORT:8088}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
