global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: streamhub
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - auth-service:8081
          - user-service:8082
          - live-service:8083
          - gateway-service:8088
          - realtime-gateway:8090
